# Generated by Django 6.1.2 on 2026-10-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.CharField(choices=[('follow', 'Follow my phone'), ('light', 'Always light'), ('dark', 'Always dark')], default='follow', max_length=10, verbose_name='dark mode'),
        ),
        migrations.AddField(
            model_name='user',
            name='plain_font',
            field=models.BooleanField(default=False, verbose_name='plain font'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('ink', 'Black ink'), ('paper', 'Paper and red marker'), ('chalk', 'Chalkboard'), ('sky', 'Light blue'), ('meadow', 'Green')], default='ink', max_length=10, verbose_name='look'),
        ),
    ]
