# Generated by Django 6.1.2 on 2026-10-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_item_changes_outlive_lists_and_reservations_outlive_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchange',
            name='kind',
            field=models.CharField(choices=[('changed', 'Changed'), ('deleted', 'Deleted'), ('removed', 'Removed')], max_length=10),
        ),
    ]
