/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/logout/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Ends the session this request was made with. */
    post: operations['auth_logout_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/request-code/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Emails a sign-in code and magic link. Answers the same way whether or not the account exists. */
    post: operations['auth_request_code_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The devices signed in to this account. `current` marks the one making the request. */
    get: operations['auth_sessions_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Signs a device out of this account. */
    delete: operations['auth_sessions_destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/verify/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Exchanges a code (or a magic-link token) for a session token. The first sign-in creates the account. */
    post: operations['auth_verify_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/devices/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Registers this phone for push notifications, or stops them. */
    post: operations['devices_create'];
    /** @description Registers this phone for push notifications, or stops them. */
    delete: operations['devices_destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/go/{token}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Opens an item's shop link for someone a list is shared with, adding Delibird's affiliate code when the
     *     shop has one. It works only through a link Delibird handed out, while the list is still shared with them
     *     and the item is still on it, so it can't send people anywhere else or reveal other items. It records
     *     nothing, so the owner can never learn who clicked.
     */
    get: operations['go_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Reports whether the API can reach its database and Redis. */
    get: operations['health_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/items/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description One item, on every list it is on. Sending `lists` sets exactly which lists it is on (it always stays
     *     on the default list). Deleting it removes it from every list.
     */
    get: operations['items_retrieve'];
    put?: never;
    post?: never;
    /**
     * @description One item, on every list it is on. Sending `lists` sets exactly which lists it is on (it always stays
     *     on the default list). Deleting it removes it from every list.
     */
    delete: operations['items_destroy'];
    options?: never;
    head?: never;
    /**
     * @description One item, on every list it is on. Sending `lists` sets exactly which lists it is on (it always stays
     *     on the default list). Deleting it removes it from every list.
     */
    patch: operations['items_partial_update'];
    trace?: never;
  };
  '/api/v1/items/{id}/image/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** @description Adds or replaces an item's picture (multipart upload), or removes it. */
    put: operations['items_image_update'];
    post?: never;
    /** @description Adds or replaces an item's picture (multipart upload), or removes it. */
    delete: operations['items_image_destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/items/{id}/image/from-url/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Downloads a picture (for example the one autofill found) and stores it as the item's picture. */
    post: operations['items_image_from_url_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/items/{id}/reservation/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Reserve an item on a list shared with you, or cancel your reservation. For anyone who can't
     *     reserve the item, the owner included, the answer is the same 404 as for an item that doesn't exist.
     */
    post: operations['items_reservation_create'];
    /**
     * @description Reserve an item on a list shared with you, or cancel your reservation. For anyone who can't
     *     reserve the item, the owner included, the answer is the same 404 as for an item that doesn't exist.
     */
    delete: operations['items_reservation_destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/items/autofill/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Reads a shop page and suggests the item's name, price, currency, description and picture. When the
     *     shop can't be read, `found` is false and the link is still returned, so it can be saved as it is.
     */
    post: operations['items_autofill_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lists/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The signed-in person's lists, default list included, in their chosen order. */
    get: operations['lists_list'];
    put?: never;
    /** @description The signed-in person's lists, default list included, in their chosen order. */
    post: operations['lists_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lists/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description One list with its items. The default list holds every item; it can be renamed but not deleted.
     *     Deleting another list takes its items off it, but keeps them on the default list.
     */
    get: operations['lists_retrieve'];
    put?: never;
    post?: never;
    /**
     * @description One list with its items. The default list holds every item; it can be renamed but not deleted.
     *     Deleting another list takes its items off it, but keeps them on the default list.
     */
    delete: operations['lists_destroy'];
    options?: never;
    head?: never;
    /**
     * @description One list with its items. The default list holds every item; it can be renamed but not deleted.
     *     Deleting another list takes its items off it, but keeps them on the default list.
     */
    patch: operations['lists_partial_update'];
    trace?: never;
  };
  '/api/v1/lists/{id}/items/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description The items on one list, in that list's order. A new item goes at the end of this list and of the
     *     default list, and of any other lists named in `lists`.
     */
    get: operations['lists_items_list'];
    put?: never;
    /**
     * @description The items on one list, in that list's order. A new item goes at the end of this list and of the
     *     default list, and of any other lists named in `lists`.
     */
    post: operations['lists_items_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lists/{id}/items/{item_id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * @description Puts one of your existing items on this list (PUT), or takes it off (DELETE). Taking an item off
     *     the default list deletes it everywhere.
     */
    put: operations['lists_items_update'];
    post?: never;
    /**
     * @description Puts one of your existing items on this list (PUT), or takes it off (DELETE). Taking an item off
     *     the default list deletes it everywhere.
     */
    delete: operations['lists_items_destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lists/{id}/items/reorder/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Sets the order of all the items on one list. */
    post: operations['lists_items_reorder_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lists/{id}/shares/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The people a list is shared with. Adding someone returns their personal link, once. */
    get: operations['lists_shares_list'];
    put?: never;
    /** @description The people a list is shared with. Adding someone returns their personal link, once. */
    post: operations['lists_shares_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lists/reorder/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Sets the order of all the signed-in person's lists. */
    post: operations['lists_reorder_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The signed-in account. Deleting it removes the account and everything that belongs to it. */
    get: operations['me_retrieve'];
    put?: never;
    post?: never;
    /** @description The signed-in account. Deleting it removes the account and everything that belongs to it. */
    delete: operations['me_destroy'];
    options?: never;
    head?: never;
    /** @description The signed-in account. Deleting it removes the account and everything that belongs to it. */
    patch: operations['me_partial_update'];
    trace?: never;
  };
  '/api/v1/shared-with-me/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Lists other people shared with you, once you accepted their link. */
    get: operations['shared_with_me_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/shared-with-me/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description One list shared with you, with which items are free, yours, or taken and by whom. */
    get: operations['shared_with_me_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/shared/{token}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description A list opened through someone's link. Needs no account, and never says which items are taken:
     *     signed-in viewers see that in "Shared with me". The owner gets the same owner-safe view.
     */
    get: operations['shared_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/shared/{token}/join/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Accepts a link: the list then appears under "Shared with me" and its items can be reserved. */
    post: operations['shared_join_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/shares/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Stops sharing with one person. Their link stops working. */
    delete: operations['shares_destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Autofill: {
      /** @description Whether anything was read. If not, keep the link and type the rest. */
      found: boolean;
      /** @description The link to save: the one sent, or where it led. */
      url: string;
      name: string;
      description: string;
      /** Format: decimal */
      price: string | null;
      currency: string | null;
      /** @description A picture to fetch with image/from-url/. */
      image_url: string | null;
    };
    Detail: {
      detail: string;
    };
    DeviceRequest: {
      token: string;
      platform: components['schemas']['PlatformEnum'];
    };
    Health: {
      status: components['schemas']['HealthStatusEnum'];
      database: boolean;
      redis: boolean;
      language: string;
      message: string;
    };
    /**
     * @description * `ok` - ok
     *     * `degraded` - degraded
     * @enum {string}
     */
    HealthStatusEnum: 'ok' | 'degraded';
    ImageUploadRequest: {
      /**
       * Format: binary
       * @description JPEG, PNG, WebP or GIF, up to 10 MB.
       */
      image: string;
    };
    Item: {
      readonly id: number;
      name: string;
      /** Link */
      url: string;
      description: string;
      rating: number | null;
      /** @description Absolute URL of the item's picture, if it has one. */
      readonly image: string | null;
      /** Format: decimal */
      price: string | null;
      currency: string;
      /** @description Every list the item is on. It is always on the default list, whether or not that is sent. */
      lists: number[];
      /** @description Whether the item is on any list someone has a link to. */
      readonly on_shared_list: boolean;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    ItemRequest: {
      name: string;
      /** Link */
      url?: string;
      description?: string;
      rating?: number | null;
      /** Format: decimal */
      price?: string | null;
      currency?: string;
      /** @description Every list the item is on. It is always on the default list, whether or not that is sent. */
      lists?: number[];
    };
    /**
     * @description * `en` - English
     *     * `it` - Italian
     *     * `es` - Spanish
     * @enum {string}
     */
    LanguageEnum: 'en' | 'it' | 'es';
    LinkRequest: {
      /** Format: uri */
      url: string;
    };
    /** @description A share as its owner sees it. */
    NewShare: {
      readonly id: number;
      /** Format: email */
      email: string;
      /** @description Whether someone has accepted the link. */
      readonly joined: boolean;
      /** @description The name of whoever accepted the link. */
      readonly joined_as: string | null;
      /** Format: date-time */
      readonly created_at: string;
      /** @description The person's own link. It is shown only once. */
      readonly link: string;
    };
    /** @description A share as its owner sees it. */
    NewShareRequest: {
      /** Format: email */
      email: string;
    };
    PatchedItemRequest: {
      name?: string;
      /** Link */
      url?: string;
      description?: string;
      rating?: number | null;
      /** Format: decimal */
      price?: string | null;
      currency?: string;
      /** @description Every list the item is on. It is always on the default list, whether or not that is sent. */
      lists?: number[];
    };
    PatchedUserRequest: {
      display_name?: string;
      language?: components['schemas']['LanguageEnum'];
    };
    PatchedWishlistDetailRequest: {
      name?: string;
    };
    /**
     * @description * `android` - Android
     *     * `ios` - Ios
     * @enum {string}
     */
    PlatformEnum: 'android' | 'ios';
    ReorderRequest: {
      /** @description Every id, in the new order. */
      ids: number[];
    };
    RequestCodeRequest: {
      /** Format: email */
      email: string;
    };
    ReservationState: {
      status: components['schemas']['ReservationStateStatusEnum'];
      /** @description Who is getting it, when someone else is. */
      by: string | null;
    };
    /**
     * @description * `free` - free
     *     * `mine` - mine
     *     * `taken` - taken
     * @enum {string}
     */
    ReservationStateStatusEnum: 'free' | 'mine' | 'taken';
    /** @enum {string} */
    RoleEnum: 'owner' | 'viewer' | 'invited' | 'anonymous';
    Session: {
      readonly id: number;
      readonly device_name: string;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly last_used_at: string;
      readonly current: boolean;
    };
    /** @description A share as its owner sees it. */
    Share: {
      readonly id: number;
      /** Format: email */
      email: string;
      /** @description Whether someone has accepted the link. */
      readonly joined: boolean;
      /** @description The name of whoever accepted the link. */
      readonly joined_as: string | null;
      /** Format: date-time */
      readonly created_at: string;
    };
    /** @description An item as people the list is shared with see it, without anything about reservations. */
    SharedItem: {
      readonly id: number;
      name: string;
      /** Link */
      url: string;
      /** @description The link to open for this item: the shop link itself, or a Delibird link that adds an affiliate code on the way. Empty when the item has no link. */
      readonly shop_url: string;
      /** @description Whether opening shop_url may earn a commission. */
      readonly affiliate: boolean;
      description: string;
      rating: number | null;
      readonly image: string | null;
      /** Format: decimal */
      price: string | null;
      currency: string;
    };
    /** @description A list opened through a share link. `role` says how the requester relates to it. */
    SharedList: {
      readonly id: number;
      name: string;
      readonly owner_name: string;
      /** @description owner: it's your list. viewer: you accepted this link. invited: sign in or accept to reserve. anonymous: not signed in. */
      readonly role: components['schemas']['RoleEnum'];
      readonly items: components['schemas']['SharedItem'][];
    };
    SignedIn: {
      /** @description Send it as `Authorization: Bearer <token>`. */
      token: string;
      user: components['schemas']['User'];
    };
    User: {
      readonly id: number;
      /** Format: email */
      readonly email: string;
      display_name: string;
      language: components['schemas']['LanguageEnum'];
    };
    /** @description Either the email and the six-digit code, or the token from the magic link. */
    VerifyRequest: {
      /** Format: email */
      email?: string;
      code?: string;
      token?: string;
      device_name?: string;
    };
    /** @description An item as a signed-in viewer sees it: with whether it is taken, and by whom. */
    ViewerItem: {
      readonly id: number;
      name: string;
      /** Link */
      url: string;
      /** @description The link to open for this item: the shop link itself, or a Delibird link that adds an affiliate code on the way. Empty when the item has no link. */
      readonly shop_url: string;
      /** @description Whether opening shop_url may earn a commission. */
      readonly affiliate: boolean;
      description: string;
      rating: number | null;
      readonly image: string | null;
      /** Format: decimal */
      price: string | null;
      currency: string;
      readonly reservation: components['schemas']['ReservationState'];
    };
    ViewerList: {
      readonly id: number;
      name: string;
      readonly owner_name: string;
      readonly item_count: number;
      readonly items: components['schemas']['ViewerItem'][];
    };
    ViewerListSummary: {
      readonly id: number;
      name: string;
      readonly owner_name: string;
      readonly item_count: number;
    };
    Wishlist: {
      readonly id: number;
      name: string;
      readonly is_default: boolean;
      readonly position: number;
      /** @description How many items the list holds. */
      readonly item_count: number;
      /** @description Whether anyone has a link to this list. */
      readonly is_shared: boolean;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    WishlistDetail: {
      readonly id: number;
      name: string;
      readonly is_default: boolean;
      readonly position: number;
      /** @description How many items the list holds. */
      readonly item_count: number;
      /** @description Whether anyone has a link to this list. */
      readonly is_shared: boolean;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
      readonly items: components['schemas']['Item'][];
    };
    WishlistRequest: {
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_request_code_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestCodeRequest'];
        'application/x-www-form-urlencoded': components['schemas']['RequestCodeRequest'];
        'multipart/form-data': components['schemas']['RequestCodeRequest'];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
    };
  };
  auth_sessions_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'][];
        };
      };
    };
  };
  auth_sessions_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_verify_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['VerifyRequest'];
        'application/x-www-form-urlencoded': components['schemas']['VerifyRequest'];
        'multipart/form-data': components['schemas']['VerifyRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SignedIn'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
    };
  };
  devices_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeviceRequest'];
        'application/x-www-form-urlencoded': components['schemas']['DeviceRequest'];
        'multipart/form-data': components['schemas']['DeviceRequest'];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  devices_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  go_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description To the shop */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown link, or no longer shared */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  health_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  items_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Item'];
        };
      };
    };
  };
  items_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  items_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedItemRequest'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedItemRequest'];
        'multipart/form-data': components['schemas']['PatchedItemRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Item'];
        };
      };
    };
  };
  items_image_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['ImageUploadRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Item'];
        };
      };
    };
  };
  items_image_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Item'];
        };
      };
    };
  };
  items_image_from_url_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LinkRequest'];
        'application/x-www-form-urlencoded': components['schemas']['LinkRequest'];
        'multipart/form-data': components['schemas']['LinkRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Item'];
        };
      };
    };
  };
  items_reservation_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No response body */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No response body */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  items_reservation_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No response body */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  items_autofill_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LinkRequest'];
        'application/x-www-form-urlencoded': components['schemas']['LinkRequest'];
        'multipart/form-data': components['schemas']['LinkRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Autofill'];
        };
      };
    };
  };
  lists_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Wishlist'][];
        };
      };
    };
  };
  lists_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WishlistRequest'];
        'application/x-www-form-urlencoded': components['schemas']['WishlistRequest'];
        'multipart/form-data': components['schemas']['WishlistRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Wishlist'];
        };
      };
    };
  };
  lists_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WishlistDetail'];
        };
      };
    };
  };
  lists_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  lists_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedWishlistDetailRequest'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedWishlistDetailRequest'];
        'multipart/form-data': components['schemas']['PatchedWishlistDetailRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WishlistDetail'];
        };
      };
    };
  };
  lists_items_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Item'][];
        };
      };
    };
  };
  lists_items_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ItemRequest'];
        'application/x-www-form-urlencoded': components['schemas']['ItemRequest'];
        'multipart/form-data': components['schemas']['ItemRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Item'];
        };
      };
    };
  };
  lists_items_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Item'];
        };
      };
    };
  };
  lists_items_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  lists_items_reorder_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderRequest'];
        'application/x-www-form-urlencoded': components['schemas']['ReorderRequest'];
        'multipart/form-data': components['schemas']['ReorderRequest'];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  lists_shares_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Share'][];
        };
      };
    };
  };
  lists_shares_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewShareRequest'];
        'application/x-www-form-urlencoded': components['schemas']['NewShareRequest'];
        'multipart/form-data': components['schemas']['NewShareRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NewShare'];
        };
      };
    };
  };
  lists_reorder_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderRequest'];
        'application/x-www-form-urlencoded': components['schemas']['ReorderRequest'];
        'multipart/form-data': components['schemas']['ReorderRequest'];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  me_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedUserRequest'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedUserRequest'];
        'multipart/form-data': components['schemas']['PatchedUserRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  shared_with_me_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ViewerListSummary'][];
        };
      };
    };
  };
  shared_with_me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ViewerList'];
        };
      };
    };
  };
  shared_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SharedList'];
        };
      };
      /** @description Unknown link */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  shared_join_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ViewerListSummary'];
        };
      };
      /** @description It's your own list */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Someone else already accepted this link */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  shares_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
