/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/logout/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Ends the session this request was made with. */
    post: operations['auth_logout_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/request-code/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Emails a sign-in code and magic link. Answers the same way whether or not the account exists. */
    post: operations['auth_request_code_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The devices signed in to this account. `current` marks the one making the request. */
    get: operations['auth_sessions_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Signs a device out of this account. */
    delete: operations['auth_sessions_destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/verify/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Exchanges a code (or a magic-link token) for a session token. The first sign-in creates the account. */
    post: operations['auth_verify_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Reports whether the API can reach its database and Redis. */
    get: operations['health_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The signed-in account. Deleting it removes the account and everything that belongs to it. */
    get: operations['me_retrieve'];
    put?: never;
    post?: never;
    /** @description The signed-in account. Deleting it removes the account and everything that belongs to it. */
    delete: operations['me_destroy'];
    options?: never;
    head?: never;
    /** @description The signed-in account. Deleting it removes the account and everything that belongs to it. */
    patch: operations['me_partial_update'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Detail: {
      detail: string;
    };
    Health: {
      status: components['schemas']['StatusEnum'];
      database: boolean;
      redis: boolean;
      language: string;
      message: string;
    };
    /**
     * @description * `en` - English
     *     * `it` - Italian
     *     * `es` - Spanish
     * @enum {string}
     */
    LanguageEnum: 'en' | 'it' | 'es';
    PatchedUserRequest: {
      display_name?: string;
      language?: components['schemas']['LanguageEnum'];
    };
    RequestCodeRequest: {
      /** Format: email */
      email: string;
    };
    Session: {
      readonly id: number;
      readonly device_name: string;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly last_used_at: string;
      readonly current: boolean;
    };
    SignedIn: {
      /** @description Send it as `Authorization: Bearer <token>`. */
      token: string;
      user: components['schemas']['User'];
    };
    /**
     * @description * `ok` - ok
     *     * `degraded` - degraded
     * @enum {string}
     */
    StatusEnum: 'ok' | 'degraded';
    User: {
      readonly id: number;
      /** Format: email */
      readonly email: string;
      display_name: string;
      language: components['schemas']['LanguageEnum'];
    };
    /** @description Either the email and the six-digit code, or the token from the magic link. */
    VerifyRequest: {
      /** Format: email */
      email?: string;
      code?: string;
      token?: string;
      device_name?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_request_code_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestCodeRequest'];
        'application/x-www-form-urlencoded': components['schemas']['RequestCodeRequest'];
        'multipart/form-data': components['schemas']['RequestCodeRequest'];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
    };
  };
  auth_sessions_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'][];
        };
      };
    };
  };
  auth_sessions_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_verify_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['VerifyRequest'];
        'application/x-www-form-urlencoded': components['schemas']['VerifyRequest'];
        'multipart/form-data': components['schemas']['VerifyRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SignedIn'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
    };
  };
  health_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  me_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedUserRequest'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedUserRequest'];
        'multipart/form-data': components['schemas']['PatchedUserRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
}
